# Generated by Django 5.1.4 on 2024-12-09 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slide', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='slide',
            table='slide',
        ),
    ]
